apiVersion: v1
kind: Pod                                           
metadata:
  name: sa-frontend                                  
spec:                                                
  containers:
    - image:  maxcxam/sentiment-analysis-frontend    
      name: sa-frontend                              
      ports:
        - containerPort: 80